### ISSUE TITLE
npm run build: events.js unhandled error event

### ISSUE THREAD

**Issue by dhimmel** [cognoma/frontend#75]
On Ubuntu 16.10 I'm getting an error when running `npm run build`. Here's the terminal output:

```
> Cognoma@0.0.0 build /home/dhimmel/Documents/greene/cognoma/frontend
> cross-env NODE_ENV=production ./node_modules/.bin/gulp prod

[15:14:10] Requiring external module babel-register
[15:14:12] Using gulpfile ~/Documents/greene/cognoma/frontend/gulpfile.babel.js
[15:14:12] Starting 'clean'...
[15:14:12] Finished 'clean' after 5.93 ms
[15:14:12] Starting 'prod'...
[15:14:12] Starting 'styles'...
[15:14:12] Starting 'images'...
[15:14:12] Starting 'fonts'...
[15:14:12] Starting 'views'...
[15:14:12] Finished 'views' after 593 μs
[15:14:12] Finished 'fonts' after 13 ms

events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/dhimmel/Documents/greene/cognoma/frontend/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 4.8.0-39-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Cognoma@0.0.0 build: `cross-env NODE_ENV=production ./node_modules/.bin/gulp prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Cognoma@0.0.0 build script 'cross-env NODE_ENV=production ./node_modules/.bin/gulp prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Cognoma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production ./node_modules/.bin/gulp prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Cognoma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Cognoma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dhimmel/.npm/_logs/2017-04-04T19_14_12_238Z-debug.log
```

Here's the error log npm suggested I include in this issue: [`2017-04-04T19_14_12_238Z-debug.log.txt`](https://github.com/cognoma/frontend/files/894241/2017-04-04T19_14_12_238Z-debug.log.txt).

**Comment by dhimmel** [comment]
I had updated my node.js and npm versions, using the [Ubuntu PPA](http://www.hostingadvice.com/how-to/update-npm-packages/).

I ran `npm rebuild` and the above issue was no longer! So I'm guessing the rebuild solved the issue.

**Comment by saschamander** [comment]
Upgrading node+npm worked for me. Thx
